services:

  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: always
    environment:
      POSTGRES_DB: taskmanager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hmctstm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: dev-task-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskmanager_db
      DB_USER_NAME: postgres
      DB_PASSWORD: hmctstm
    ports:
      - "4000:4000"

volumes:
  postgres_data:
